
ACME_DIST=../acme_dao/dist

RUNTIME_CLASSPATH=.
RUNTIME_CLASSPATH=$HSQLDB_HOME/lib/hsqldb.jar:$RUNTIME_CLASSPATH
RUNTIME_CLASSPATH=$RUNTIME_CLASSPATH:$ACME_DIST/acme-flagship-dao-1.0.jar
RUNTIME_CLASSPATH=$RUNTIME_CLASSPATH:$ACME_DIST/antlr-2.7.7.jar
RUNTIME_CLASSPATH=$RUNTIME_CLASSPATH:$ACME_DIST/dom4j-1.6.1.jar
RUNTIME_CLASSPATH=$RUNTIME_CLASSPATH:$ACME_DIST/hibernate-commons-annotations-4.0.5.Final.jar
RUNTIME_CLASSPATH=$RUNTIME_CLASSPATH:$ACME_DIST/hibernate-core-4.3.10.Final.jar
RUNTIME_CLASSPATH=$RUNTIME_CLASSPATH:$ACME_DIST/hibernate-entitymanager-4.3.10.Final.jar
RUNTIME_CLASSPATH=$RUNTIME_CLASSPATH:$ACME_DIST/hibernate-jpa-2.1-api-1.0.0.Final.jar
RUNTIME_CLASSPATH=$RUNTIME_CLASSPATH:$ACME_DIST/jandex-1.1.0.Final.jar
RUNTIME_CLASSPATH=$RUNTIME_CLASSPATH:$ACME_DIST/javassist-3.18.1-GA.jar
RUNTIME_CLASSPATH=$RUNTIME_CLASSPATH:$ACME_DIST/jboss-logging-3.1.3.GA.jar
RUNTIME_CLASSPATH=$RUNTIME_CLASSPATH:$ACME_DIST/jboss-logging-annotations-1.2.0.Beta1.jar
RUNTIME_CLASSPATH=$RUNTIME_CLASSPATH:$ACME_DIST/jboss-transaction-api_1.2_spec-1.0.0.Final.jar
RUNTIME_CLASSPATH=$RUNTIME_CLASSPATH:$ACME_DIST/slf4j-api-1.7.7.jar
RUNTIME_CLASSPATH=$RUNTIME_CLASSPATH:$ACME_DIST/slf4j-simple-1.7.7.jar
# RUNTIME_CLASSPATH=$RUNTIME_CLASSPATH:$ACME_DIST/xml-apis-1.0.b2.jar

groovy -cp $RUNTIME_CLASSPATH WebServer.groovy
